##########################     OUTPUT FILE OPTIONS    ##########################

output_fname: 'XAMBG_1011' # output base filename
num_frames: 1200 # number of range-doppler map frames to compute

##########################    INPUT DATA PARAMETERS    #########################

input_sample_rate: 2400000 # input sample rate in Hz

#########################    PROCESSING PARAMETERS    ##########################

# Nominal value for the coherent processing interval (CPI) in seconds. The doppler 
# resolution is inversely proportional to this, i.e. a 2 second CPI corresponds
# to a Doppler resolution of 0.5Hz.
cpi_seconds_nominal: 0.5 
max_doppler_nominal: 100.0  # The maximum desired doppler shift in Hz. 
max_range_nominal: 5.0    # The maximum desired bistatic range in km.
overlap_cpi: True           # whether to overlap CPI windows. 
